In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy import stats
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
import os
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import matplotlib.pyplot as plt
from sklearn.model_selection import RandomizedSearchCV
import seaborn as sns
from sklearn.metrics import accuracy_score
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.model_selection import GridSearchCV, StratifiedShuffleSplit
from xgboost.sklearn import XGBClassifier
from sklearn.ensemble import RandomForestClassifier
from scipy.special import entr
from sklearn import preprocessing
import matplotlib.pyplot as plt
import math
import seaborn as sns
from sklearn.metrics import accuracy_score
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from IPython.display import display
#import itertools
#from itables import init_notebook_mode
import random
#init_notebook_mode(all_interactive=True)

In [2]:
os.chdir('./datasets')
arr = os.listdir()
files_dict = {}


for i in arr:
    #print(i)
    print(i)
    if i == ".DS_Store":
        continue
    os.chdir(i)

    arr2 = os.listdir()
    print(len(arr2))

    if len(arr2) != 0:

        print(arr2)
        w = './training'
        os.chdir(w)
        arr3 = os.listdir()


        files_dict[i] = arr3
        

        os.chdir('../')

    os.chdir('../')
    print(os.listdir())


os.chdir('../')

1
1
['training']
['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '3', '4', '5', '6', '7', '8', '9']
10
1
['training']
['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '3', '4', '5', '6', '7', '8', '9']
11
1
['training']
['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '3', '4', '5', '6', '7', '8', '9']
12
1
['training']
['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '3', '4', '5', '6', '7', '8', '9']
13
1
['training']
['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '3', '4', '5', '6', '7', '8', '9']
14
1
['training']
['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '3', '4', '5', '6', '7', '8', '9']
15
1
['training']
['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '3', '4', '5', '6', '7', '8', '9']
16
1
['training']
['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '3', '4', '5', '6', '7', '8', '9']
17
1
['training']
['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '3', '4', '5', '6', '7', '8', '9']
18
1
['training']
['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '3', '4', '5', '6', '7', '8', '9']
19
1
['training']
['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '3', '4', '5', '6', '7', '8', '9']
2
1
['training']
['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '3', '4', '5', '6', '7', '8', '9']
3
1
['training']
['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '3', '4', '5', '6', '7', '8', '9']
4
1
['training']
['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '3', '4', '5', '6', '7', '8', '9']
5
1
['training']
['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '3', '4', '5', '6', '7', '8', '9']
6
1
['training']
['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '3', '4', '5', '6', '7', '8', '9']
7
1
['training']
['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '3', '4', '5', '6', '7', '8', '9']
8
1
['training']
['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '3', '4', '5', '6', '7', '8', '9']
9
1
['training']
['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '3', '4', '5', '6', '7', '8', '9']

In [3]:
# Take the first three elements of files_dict and print them
#print(list(files_dict.keys())[:3])
# Store the printed elements in a list with keys and associated values
keys = list(files_dict.keys())
values = list(files_dict.values())
# Create a new dictionaries from these lists
new_dict_2 = dict(zip(keys, values))
#print(new_dict_2)
files_dict.keys()
#del files_dict
del keys
del values

In [4]:
user_dict = {}
user_dict_by_category = {}
all_category = ['office\n', 'file system\n', 'browsing\n', 'gaming\n', 'entertainment\n', 'development\n']



for i in list(new_dict_2.keys()):
    user_dict[i] = []
    user_dict_by_category[i] = {}
    for category in all_category:
        user_dict_by_category[i][category] = []

    #count = 1
    for j in list(files_dict[i]):

        #user_dict[i][count] = None
        w = './datasets/' + i + '/training/' + j
        file1 = open(w, 'r')
        Lines = file1.readlines()
        txt_array = []
        for k in range(0, len(Lines)):
            #print(Lines[k].split(","))
            txt_array.append(Lines[k].split(","))

        tmpp = pd.DataFrame(txt_array[1:], columns=txt_array[0])
        tmpp['timestamp'] = [int(i[0])*1000 + int(str(i[1])[:3].ljust(3, '0')) for i in tmpp['client_timestamp'].str.split('.')]
        uniquess = tmpp['window\n'].unique().tolist()
        #        print(uniquess)

        #tmpp = tmpp[tmpp['window\n'] == 'browsing\n']
        tmpp = tmpp[tmpp['state'] == "Move"]
        user_dict[i].append(tmpp)
        # for k in all_category:
        #     tmpp = tmpp[tmpp['window\n'] == k]
        #     #tmpp = tmpp[tmpp['state'] == "Move"]
        #     if tmpp.empty:
        #         user_dict_by_category[i][k].append(tmpp)
del tmpp

In [30]:
# Extract maximum timestamp for user 1 for the first session
maximum = user_dict['1'][0]['timestamp'].max()
# Extract minimum timestamp for user 1 for the first session
minimum = user_dict['1'][0]['timestamp'].min()
# Calculate the difference between the maximum and minimum timestamp
difference = maximum - minimum
# Print the difference in hours
print(difference / (1000 * 60 * 60))


#user_dict['1'][0]['timestamp']

17.319804444444443

In [5]:
def modify_timestamps(dfs):
    modified_dfs = []
    for df in dfs:
        if not df.empty:
            df['timestamp_modified'] = df['timestamp'].iloc[0] + df.index * 10
        modified_dfs.append(df)
    return modified_dfs

In [6]:
# Create temporary dictionary to store modified dataframes
temp_dict = {}
# For loop that calls mofify_timestamp function on each list of user's dataframe
for user in user_dict:
    temp_dict[user] = modify_timestamps(user_dict[user])

In [7]:
# delete user 6
del temp_dict['6']
# delete user 18
del temp_dict['18']

In [8]:
result_dict = {}

# Iterate through the dictionary
for key, df_list in temp_dict.items():
    divided_dfs_list = []
    
    # Iterate through the list of dataframes
    for df in df_list:
        # Sort dataframe by 'timestamp_modified'
        df = df.sort_values(by='timestamp_modified')
        
        # Find the minimum and maximum timestamps
        min_timestamp = df['timestamp_modified'].min()
        max_timestamp = df['timestamp_modified'].max()
        
        # Divide the dataframe into 5-minute intervals (300,000 ms)
        interval_start = min_timestamp
        while interval_start <= max_timestamp:
            interval_end = interval_start + 10000
            
            # Filter rows within the 5-minute interval
            mask = (df['timestamp_modified'] >= interval_start) & (df['timestamp_modified'] < interval_end)
            divided_df = df[mask]
            
            if not divided_df.empty:
                divided_dfs_list.append(divided_df)
            
            interval_start = interval_end
            
    result_dict[key] = divided_dfs_list

In [43]:
result_dict['1'][0]

,client_timestamp,x,y,button,state,window\n,timestamp,timestamp_modified,delta_x,delta_y,delta_t,distance,speed
0,1570169899.971,694.0,489.0,None,Move,browsing\n,1.570170e+12,1570169899971,NaN,NaN,NaN,NaN,NaN
1,1570169899.99,703.0,473.0,None,Move,browsing\n,1.570170e+12,1570169899981,9.0,-16.0,19.0,18.357560,0.966187
2,1570169900.0089998,713.0,454.0,None,Move,browsing\n,1.570170e+12,1570169899991,10.0,-19.0,18.0,21.470911,1.192828
3,1570169900.028,725.0,436.0,None,Move,browsing\n,1.570170e+12,1570169900001,12.0,-18.0,20.0,21.633308,1.081665
4,1570169900.046,737.0,417.0,None,Move,browsing\n,1.570170e+12,1570169900011,12.0,-19.0,18.0,22.472205,1.248456
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1570169929.641,735.0,211.0,None,Move,browsing\n,1.570170e+12,1570169909921,0.0,19.0,8.0,19.000000,2.375000
996,1570169929.647,736.0,231.0,None,Move,browsing\n,1.570170e+12,1570169909931,1.0,20.0,6.0,20.024984,3.337497
997,1570169929.654,737.0,249.0,None,Move,browsing\n,1.570170e+12,1570169909941,1.0,18.0,7.0,18.027756,2.575394
998,1570169929.661,737.0,257.0,None,Move,browsing\n,1.570170e+12,1570169909951,0.0,8.0,7.0,8.000000,1.142857
999,1570169929.669,736.0,261.0,None,Move,browsing\n,1.570170e+12,1570169909961,-1.0,4.0,8.0,4.123106,0.515388

In [ ]:
def calculate_features(df):
    # Calculate differences in x, y, and timestamp
    # Convert df['x'] and df['y'] to float
    df['x'] = df['x'].astype(float)
    df['y'] = df['y'].astype(float)
    # Also timestamp
    df['timestamp_modified'] = df['timestamp_modified'].astype(float)

    df['delta_x'] = df['x'].diff()
    df['delta_y'] = df['y'].diff()
    df['delta_t'] = df['timestamp_modified'].diff()

    # Calculate distance and speed
    df['distance'] = np.sqrt(df['delta_x'] ** 2 + df['delta_y'] ** 2)
    df['speed'] = df['distance'] / df['delta_t']

    # Position-based features
    total_distance = df['distance'].sum()
    average_speed = df['speed'].mean()
    max_speed = df['speed'].max()
    min_speed = df['speed'].min()
    std_speed = df['speed'].std()
    
    # Return a dictionary of features
    features = {'total_distance': total_distance,
                'average_speed': average_speed,
                'max_speed': max_speed,
                'min_speed': min_speed,
                'std_speed': std_speed}
    
    return features


def process_dataframes_dict(dataframes_dict):
    features_dict = {}
    
    for user, dataframes in dataframes_dict.items():
        user_features = []
        
        for df in dataframes:
            user_features.append(calculate_features(df))
        print(user_features)
        features_dict[user] = user_features
    
    return features_dict

ttt = process_dataframes_dict(result_dict)
print(ttt)

In [15]:
dict_list = []
for key, value_list in ttt.items():
    for item in value_list:
        item_with_label = item.copy()  # Make a copy to avoid modifying the original dictionary
        item_with_label['label'] = key
        dict_list.append(item_with_label)

# Create a DataFrame
df = pd.DataFrame(dict_list)

       total_distance  average_speed   max_speed  min_speed  std_speed label
0         9171.666865       0.932857    7.665507        0.0   1.323930     1
1         3228.463963       0.323598    2.184033        0.0   0.403567     1
2         3382.416041       0.338163    2.523886        0.0   0.424782     1
3         4978.571850       0.526105    4.201190        0.0   0.608073     1
4         5802.033720       0.587099    5.756735        0.0   0.712671     1
...               ...            ...         ...        ...        ...   ...
72518    18286.491515       1.867489  168.606791        0.0   6.056663     9
72519     7910.099595       0.686119   54.806974        0.0   2.065425     9
72520    11501.045471       0.997562   26.236616        0.0   2.117532     9
72521    14019.621108       1.444708   89.675861        0.0   3.931872     9
72522     7051.359797       1.635365   55.307675        0.0   4.262583     9

[72523 rows x 6 columns]

In [16]:
# Print different values for label column
user_labels = df['label'].unique()
data = df
df.to_csv('my_dict2.csv', index=False)
# Rename label column to user
#data = data.rename(columns={'label': 'user'})
from sklearn.impute import SimpleImputer
# Preprocess your data: replace missing values and infinite values with the mean of the column
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
data.iloc[:, :] = imputer.fit_transform(data.replace([np.inf, -np.inf], np.nan))

In [27]:
def run_random_forest(data, user_labels, isomap_applied=False):
    all_y_test = []
    all_y_pred = []

    for target_user in user_labels:
        user_data = data[data['label'] == target_user]
        impostor_data = data[data['label'] != target_user]

        min_samples = min(user_data.shape[0], impostor_data.shape[0])

        balanced_user_data = user_data.sample(min_samples)
        balanced_impostor_data = impostor_data.sample(min_samples)

        balanced_data = pd.concat([balanced_user_data, balanced_impostor_data]).sample(frac=1).reset_index(drop=True)

        balanced_data['label'] = np.where(balanced_data['label'] == target_user, 0, 1)

        X = balanced_data.drop(['label'], axis=1)
        y = balanced_data['label']

        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

        # Perform RFE with Random Forest estimator
        estimator = RandomForestClassifier(n_estimators=100, random_state=42)
        selector = RFE(estimator, n_features_to_select=30, step=5)
        selector.fit(X_train, y_train)

        # Get the selected features and transform the train and test sets
        X_train_selected = selector.transform(X_train)
        X_test_selected = selector.transform(X_test)

        # Train the Random Forest classifier on the selected features
        rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
        rf_classifier.fit(X_train_selected, y_train)

        y_pred = rf_classifier.predict(X_test_selected)

        all_y_test.extend(y_test)
        all_y_pred.extend(y_pred)

    print(f"{'With' if isomap_applied else 'Without'} Isomap:")
    print(classification_report(all_y_test, all_y_pred))
    print()

In [30]:
run_random_forest(data, user_labels)

ValueError: With n_samples=0, test_size=0.2 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

In [29]:
user_labels

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '19', '2',
       '3', '4', '5', '7', '8', '9'], dtype=object)

In [ ]:
def calculate_features_step3(df):
    df['delta_x'] = df['x'].diff()
    df['delta_y'] = df['y'].diff()
    df['delta_t'] = df['timestamp_modified'].diff()

    df['distance'] = np.sqrt(df['delta_x'] ** 2 + df['delta_y'] ** 2)
    df['speed'] = df['distance'] / df['delta_t']

    # Direction-based features
    df['angle'] = np.arctan2(df['delta_y'], df['delta_x'])
    df['angle_change'] = df['angle'].diff()
    df['direction_change'] = np.abs(df['angle_change'])
    
    angle_changes_sum = df['angle_change'].abs().sum()
    direction_changes_sum = df['direction_change'].sum()

    return {
        'angle_changes_sum': angle_changes_sum,
        'direction_changes_sum': direction_changes_sum,
    }

def process_dataframes_dict_step3(dataframes_dict):
    features_dict = {}
    
    for user, dataframes in dataframes_dict.items():
        user_features = []
        
        for df in dataframes:
            user_features.append(calculate_features_step3(df))
        
        features_dict[user] = user_features
    
    return features_dict

ttt_step3 = process_dataframes_dict_step3(result_dict)
print(ttt_step3)

In [17]:
run_random_forest(data, user_labels)

NameError: name 'run_random_forest' is not defined